"""
neuralgeom.paths — data and output locations.
=============================================

All scripts import their data and output locations from here instead of
recomputing them.

    from neuralgeom.paths import DATA_DIR, fig_dir
    fig = fig_dir("neural")                # -> outputs/figures/neural

Data location. ``DATA_DIR`` is the read-only directory holding the recordings.
Resolution order, first match wins:

  1. the ``NEURALGEOM_DATA_DIR`` environment variable, if set and non-empty;
  2. the first non-comment line of ``<repo>/data_dir.local`` (gitignored;
     copy ``data_dir.local.example`` and edit it);
  3. ``<repo>/SampleData``.

``DATA_DIR_SOURCE`` records which rule applied and ``describe_paths()`` prints
the resolved layout. ``DATA_DIR`` is never created: it is read-only input, and
silently creating an empty directory would mask a missing mount.

Outputs. Everything generated lands under ``outputs/``: ``figures/``,
``pdf/``, ``checkpoints/``, ``cache/``. Figures live in three flat folders,
``outputs/figures/{demos, rnn, neural}``, one per script family; the analysis
is identified by the filename prefix rather than by a subfolder. ``fig_dir``
maps a script or family name onto the right folder.
"""
from __future__ import annotations

import os
from pathlib import Path

__all__ = ["PROJECT_ROOT", "DATA_DIR", "DATA_DIR_SOURCE", "OUTPUT_DIR",
           "FIG_ROOT", "PDF_DIR", "CKPT_DIR", "CACHE_DIR", "FIG_FAMILIES",
           "fig_family", "fig_dir", "session_path", "describe_paths"]

#: repository root (the directory containing the ``neuralgeom`` package)
PROJECT_ROOT = Path(__file__).resolve().parents[1]

#: gitignored one-line override file, sitting next to pyproject.toml
_DATA_DIR_MARKER = "data_dir.local"

#: environment variable checked before anything else
_DATA_DIR_ENV = "NEURALGEOM_DATA_DIR"


def _resolve_data_dir() -> tuple[Path, str]:
    """Locate the read-only recordings directory for THIS machine.

    Returns ``(path, source)`` where *source* is a short human-readable string
    naming which resolution rule fired. See the module docstring for the
    order. Deliberately does no existence check: a missing network mount
    should surface at the point of use, with a message naming the path and
    where that path came from, rather than at import time.
    """
    env = os.environ.get(_DATA_DIR_ENV, "").strip().lstrip("\ufeff").strip('"')
    if env:
        return Path(env).expanduser(), f"env:{_DATA_DIR_ENV}"

    marker = PROJECT_ROOT / _DATA_DIR_MARKER
    if marker.exists():
        # utf-8-sig, not utf-8: Windows PowerShell 5.1's `Set-Content -Encoding
        # UTF8` and Notepad both prepend a byte-order mark (U+FEFF). It is
        # invisible, str.strip() does NOT remove it (it is not whitespace), and
        # the result is a path that looks correct in every error message while
        # never existing.
        for raw in marker.read_text(encoding="utf-8-sig").splitlines():
            line = raw.strip().lstrip("\ufeff").strip().strip('"').strip("'")
            if line and not line.startswith("#"):
                return Path(line).expanduser(), f"file:{_DATA_DIR_MARKER}"

    return PROJECT_ROOT / "SampleData", "default:<repo>/SampleData"


#: raw recordings (read-only, never created by this module)
DATA_DIR, DATA_DIR_SOURCE = _resolve_data_dir()

#: everything generated by an analysis goes under here
OUTPUT_DIR = PROJECT_ROOT / "outputs"
FIG_ROOT = OUTPUT_DIR / "figures"
PDF_DIR = OUTPUT_DIR / "pdf"
CKPT_DIR = OUTPUT_DIR / "checkpoints"
CACHE_DIR = OUTPUT_DIR / "cache"

#: the only three figure folders (see module docstring)
FIG_FAMILIES = ("demos", "rnn", "neural")

for _d in (OUTPUT_DIR, FIG_ROOT, PDF_DIR, CKPT_DIR, CACHE_DIR):
    _d.mkdir(parents=True, exist_ok=True)


def fig_family(name: str) -> str:
    """Map a script or family name onto one of the three figure families."""
    if name in FIG_FAMILIES:
        return name
    if name.startswith(("neural", "qc")):
        return "neural"
    if name.startswith(("exp_", "rnn")):
        return "rnn"
    return "demos"


def fig_dir(name: str) -> Path:
    """Figure directory for one script (a family folder, created if needed).
    The analysis is identified by the filename prefix, not by a subfolder."""
    d = FIG_ROOT / fig_family(name)
    d.mkdir(parents=True, exist_ok=True)
    return d


def describe_paths() -> str:
    """Human-readable dump of the resolved layout, for checking a new machine."""
    lines = [
        f"PROJECT_ROOT     {PROJECT_ROOT}",
        f"DATA_DIR         {DATA_DIR}",
        f"  resolved from  {DATA_DIR_SOURCE}",
        f"  exists         {DATA_DIR.exists()}",
    ]
    if DATA_DIR.exists():
        n = len(list(DATA_DIR.glob('*.h5')))
        lines.append(f"  .h5 files      {n}")
    lines += [
        f"OUTPUT_DIR       {OUTPUT_DIR}",
        f"FIG_ROOT         {FIG_ROOT}",
        f"PDF_DIR          {PDF_DIR}",
        f"CKPT_DIR         {CKPT_DIR}",
        f"CACHE_DIR        {CACHE_DIR}",
    ]
    return "\n".join(lines)


def session_path(session_id: str) -> Path:
    """Absolute path to a recording, with or without the .h5 suffix."""
    p = DATA_DIR / (session_id if session_id.endswith(".h5")
                    else f"{session_id}.h5")
    if p.exists():
        return p

    if not DATA_DIR.exists():
        raise FileNotFoundError(
            f"The data directory {DATA_DIR} does not exist "
            f"(resolved from {DATA_DIR_SOURCE}).\n"
            f"On this machine, either set the {_DATA_DIR_ENV} environment "
            f"variable, or copy 'data_dir.local.example' to "
            f"'{_DATA_DIR_MARKER}' in the repository root and put the correct "
            f"absolute path in it. If the path looks right, check that the "
            f"network share is actually mounted."
        )

    available = sorted(x.stem for x in DATA_DIR.glob('*.h5'))
    raise FileNotFoundError(
        f"{p} not found. {DATA_DIR} (from {DATA_DIR_SOURCE}) holds "
        f"{len(available)} recording(s): {available[:5]}"
        f"{' ...' if len(available) > 5 else ''}"
    )
