"""
neuralgeom.paths — single source of truth for where things live.
============================================================

Before this module every script recomputed the project root with its own
``Path(__file__).parents[n]`` and invented its own output directory, which
meant a script could not be moved without breaking. Import from here instead.

    from neuralgeom.paths import DATA_DIR, fig_dir
    fig = fig_dir("neural_stage4a")        # -> outputs/figures/neural

DATA LOCATION (v0.5.1). ``DATA_DIR`` is no longer hardwired inside the
repository. The repository is expected to live on fast local disk while the
recordings live on a lab network share, and the share may be mounted at a
different path on each workstation. Resolution order, first match wins:

  1. the ``NEURALGEOM_DATA_DIR`` environment variable, if set and non-empty;
  2. the first non-comment line of ``<repo>/data_dir.local`` (gitignored —
     copy ``data_dir.local.example`` and edit it per machine);
  3. ``<repo>/SampleData`` — the historical default, so an existing checkout
     that keeps data beside the code keeps working unchanged.

``DATA_DIR_SOURCE`` records which of the three applied; ``describe_paths()``
prints the whole resolved layout, which is the fastest way to diagnose a
"file not found" on a machine you have not used in a while. Note that
``DATA_DIR`` is NEVER created — it is read-only input, and silently making an
empty directory would mask a missing network mount.

FIGURE LAYOUT (deliberately FLAT). Figures live in just three folders —
``outputs/figures/{demos, rnn, neural}`` — one per pipeline family, with NO
per-stage subfolders: every filename already carries its stage prefix
(``qc1_``, ``s3b_``, ``cd_1_``, ``gr_step1_``, ``dynamics_real_``, ...), so
deep nesting only made browsing harder. ``fig_dir`` still accepts the old
stage names (``"neural_stage4a"``, ``"exp_context_decision"``, ...) and maps
them onto the right family folder, so no analysis script needs to know about
this.

SINGLE ARTEFACT FOLDER (v0.4.1). ``outputs/`` is the ONE place anything
generated may land: ``figures/``, ``pdf/``, ``checkpoints/``, ``cache/``.
The legacy top-level ``results/`` folder was merged into it (its artefacts
moved to ``outputs/checkpoints/best_rnn_*`` and ``outputs/cache/
{flow_reality_*, lds_cases_*, rnn_folds_percall.jsonl}``; its markdown run
notes were folded into HANDOFF.md). Never create a sibling results folder --
write through OUTPUT_DIR / CKPT_DIR / CACHE_DIR / fig_dir() instead.
"""
from __future__ import annotations

import os
from pathlib import Path

__all__ = ["PROJECT_ROOT", "DATA_DIR", "DATA_DIR_SOURCE", "OUTPUT_DIR",
           "FIG_ROOT", "PDF_DIR", "CKPT_DIR", "CACHE_DIR", "FIG_FAMILIES",
           "fig_family", "fig_dir", "session_path", "describe_paths"]

#: repository root (the directory containing the ``neuralgeom`` package)
PROJECT_ROOT = Path(__file__).resolve().parents[1]

#: gitignored one-line override file, sitting next to pyproject.toml
_DATA_DIR_MARKER = "data_dir.local"

#: environment variable checked before anything else
_DATA_DIR_ENV = "NEURALGEOM_DATA_DIR"


def _resolve_data_dir() -> tuple[Path, str]:
    """Locate the read-only recordings directory for THIS machine.

    Returns ``(path, source)`` where *source* is a short human-readable string
    naming which resolution rule fired. See the module docstring for the
    order. Deliberately does no existence check: a missing network mount
    should surface at the point of use, with a message naming the path and
    where that path came from, rather than at import time.
    """
    env = os.environ.get(_DATA_DIR_ENV, "").strip().lstrip("\ufeff").strip('"')
    if env:
        return Path(env).expanduser(), f"env:{_DATA_DIR_ENV}"

    marker = PROJECT_ROOT / _DATA_DIR_MARKER
    if marker.exists():
        # utf-8-sig, not utf-8: Windows PowerShell 5.1's `Set-Content -Encoding
        # UTF8` and Notepad both prepend a byte-order mark (U+FEFF). It is
        # invisible, str.strip() does NOT remove it (it is not whitespace), and
        # the result is a path that looks correct in every error message while
        # never existing. Learned the hard way.
        for raw in marker.read_text(encoding="utf-8-sig").splitlines():
            line = raw.strip().lstrip("\ufeff").strip().strip('"').strip("'")
            if line and not line.startswith("#"):
                return Path(line).expanduser(), f"file:{_DATA_DIR_MARKER}"

    return PROJECT_ROOT / "SampleData", "default:<repo>/SampleData"


#: raw recordings (read-only, never created by this module)
DATA_DIR, DATA_DIR_SOURCE = _resolve_data_dir()

#: everything generated by an analysis goes under here
OUTPUT_DIR = PROJECT_ROOT / "outputs"
FIG_ROOT = OUTPUT_DIR / "figures"
PDF_DIR = OUTPUT_DIR / "pdf"
CKPT_DIR = OUTPUT_DIR / "checkpoints"
CACHE_DIR = OUTPUT_DIR / "cache"

#: the only three figure folders (see module docstring)
FIG_FAMILIES = ("demos", "rnn", "neural")

for _d in (OUTPUT_DIR, FIG_ROOT, PDF_DIR, CKPT_DIR, CACHE_DIR):
    _d.mkdir(parents=True, exist_ok=True)


def fig_family(name: str) -> str:
    """Map an analysis/stage name onto one of the three figure families."""
    if name in FIG_FAMILIES:
        return name
    if name.startswith(("neural", "qc")):
        return "neural"
    if name.startswith(("exp_", "rnn")):
        return "rnn"
    return "demos"


def fig_dir(name: str) -> Path:
    """Figure directory for one analysis stage (a FAMILY folder, created if
    needed). Stage identity lives in the FILENAME prefix, not in a subfolder."""
    d = FIG_ROOT / fig_family(name)
    d.mkdir(parents=True, exist_ok=True)
    return d


def describe_paths() -> str:
    """Human-readable dump of the resolved layout, for sanity-checking a new
    machine. ``python -c "from neuralgeom.paths import describe_paths as d;
    print(d())"`` answers "why can it not find my data" in one line."""
    lines = [
        f"PROJECT_ROOT     {PROJECT_ROOT}",
        f"DATA_DIR         {DATA_DIR}",
        f"  resolved from  {DATA_DIR_SOURCE}",
        f"  exists         {DATA_DIR.exists()}",
    ]
    if DATA_DIR.exists():
        n = len(list(DATA_DIR.glob('*.h5')))
        lines.append(f"  .h5 files      {n}")
    lines += [
        f"OUTPUT_DIR       {OUTPUT_DIR}",
        f"FIG_ROOT         {FIG_ROOT}",
        f"PDF_DIR          {PDF_DIR}",
        f"CKPT_DIR         {CKPT_DIR}",
        f"CACHE_DIR        {CACHE_DIR}",
    ]
    return "\n".join(lines)


def session_path(session_id: str) -> Path:
    """Absolute path to a recording, with or without the .h5 suffix."""
    p = DATA_DIR / (session_id if session_id.endswith(".h5")
                    else f"{session_id}.h5")
    if p.exists():
        return p

    if not DATA_DIR.exists():
        raise FileNotFoundError(
            f"The data directory {DATA_DIR} does not exist "
            f"(resolved from {DATA_DIR_SOURCE}).\n"
            f"On this machine, either set the {_DATA_DIR_ENV} environment "
            f"variable, or copy 'data_dir.local.example' to "
            f"'{_DATA_DIR_MARKER}' in the repository root and put the correct "
            f"absolute path in it. If the path looks right, check that the "
            f"network share is actually mounted."
        )

    available = sorted(x.stem for x in DATA_DIR.glob('*.h5'))
    raise FileNotFoundError(
        f"{p} not found. {DATA_DIR} (from {DATA_DIR_SOURCE}) holds "
        f"{len(available)} recording(s): {available[:5]}"
        f"{' ...' if len(available) > 5 else ''}"
    )
