"""
neuralgeom.stats — permutation tests and shuffles for geometry claims.
==================================================================

Geometric quantities are estimated from fitted models, so almost all of them
have a non-zero value even when there is nothing to find. Every claim
therefore needs its own null, generated by the identical pipeline. This module
holds the tests and the shuffle constructors so that scripts cannot quietly
use different ones.

TESTS
-----
mantel                 correlation between two DISTANCE matrices, with a null
                       from permuting condition labels. Ordinary correlation
                       is invalid on pairwise distances because pairs sharing
                       a condition are dependent; Mantel preserves that
                       dependence exactly. NOTE the resolution floor: with n
                       conditions there are only n! orderings, so the smallest
                       attainable p is about 1/n! (0.04 at n=4).
partial_mantel         the same, after linearly regressing a confound
                       distance matrix out of both inputs.
empirical_p            two-sided p from a null sample; floors at
                       1/(n_draws+1), so report effect size in null-SD units
                       when draws are few.

SHUFFLES (each destroys one specific structure, preserving the rest)
--------
shuffle_trials         permute a per-trial variable across trials. Breaks the
                       state->behaviour link; keeps each trial's activity and
                       its internal time course intact.
circular_shift         roll each trial's activity in time by a random offset.
                       Destroys state->time while preserving every unit's
                       autocorrelation and the population covariance exactly.
within_bin_shuffle     independently permute trial identity within each time
                       bin. Destroys single-trial correspondence but preserves
                       the mean trajectory and each bin's covariance, so it
                       isolates single-trial information from the condition
                       average.
"""
from __future__ import annotations

from typing import Callable, Tuple

import numpy as np

__all__ = ["mantel", "partial_mantel", "empirical_p", "shuffle_trials",
           "circular_shift", "within_bin_shuffle", "null_summary"]


def _upper(D: np.ndarray) -> np.ndarray:
    return D[np.triu_indices(D.shape[0], 1)]


def mantel(D1: np.ndarray, D2: np.ndarray, n_perm: int = 2000, seed: int = 0
           ) -> Tuple[float, float, np.ndarray]:
    """Returns (r, two-sided p, null distribution)."""
    n = D1.shape[0]
    iu = np.triu_indices(n, 1)
    r = float(np.corrcoef(D1[iu], D2[iu])[0, 1])
    rng = np.random.default_rng(seed)
    null = np.empty(n_perm)
    for i in range(n_perm):
        p = rng.permutation(n)
        null[i] = np.corrcoef(D1[iu], D2[np.ix_(p, p)][iu])[0, 1]
    return r, float((np.abs(null) >= abs(r)).mean()), null


def partial_mantel(D1: np.ndarray, D2: np.ndarray, Dc: np.ndarray,
                   n_perm: int = 2000, seed: int = 0) -> Tuple[float, float]:
    """Mantel after regressing the confound matrix Dc out of both inputs."""
    n = D1.shape[0]
    iu = np.triu_indices(n, 1)

    def resid(a, c):
        A = np.vstack([c, np.ones_like(c)]).T
        return a - A @ np.linalg.lstsq(A, a, rcond=None)[0]

    c = Dc[iu]
    r = float(np.corrcoef(resid(D1[iu], c), resid(D2[iu], c))[0, 1])
    rng = np.random.default_rng(seed)
    null = np.empty(n_perm)
    for i in range(n_perm):
        p = rng.permutation(n)
        null[i] = np.corrcoef(resid(D1[iu], c),
                              resid(D2[np.ix_(p, p)][iu], c))[0, 1]
    return r, float((np.abs(null) >= abs(r)).mean())


def empirical_p(observed: float, null: np.ndarray) -> float:
    """Two-sided empirical p with the +1 correction. Floors at 1/(n+1)."""
    null = np.asarray(null, float)
    c = np.mean(null)
    return float((np.sum(np.abs(null - c) >= abs(observed - c)) + 1)
                 / (len(null) + 1))


# ---------------------------- shuffles ------------------------------------- #
def shuffle_trials(v: np.ndarray, seed: int = 0) -> np.ndarray:
    """Permute a per-trial variable across trials."""
    return np.random.default_rng(seed).permutation(np.asarray(v))


def circular_shift(X: np.ndarray, seed: int = 0) -> np.ndarray:
    """Roll each trial in time by an independent random offset.

    X : (trials, time, units). Preserves each unit's autocorrelation and the
    covariance structure; destroys the relationship to trial time.
    """
    rng = np.random.default_rng(seed)
    out = np.empty_like(X)
    for i in range(X.shape[0]):
        out[i] = np.roll(X[i], int(rng.integers(1, X.shape[1])), axis=0)
    return out


def within_bin_shuffle(X: np.ndarray, seed: int = 0) -> np.ndarray:
    """Permute trial identity independently within each time bin.

    X : (trials, time, units). Preserves the mean trajectory and every bin's
    across-trial covariance; destroys which trial a state belongs to.
    """
    rng = np.random.default_rng(seed)
    out = np.empty_like(X)
    for t in range(X.shape[1]):
        out[:, t, :] = X[rng.permutation(X.shape[0]), t, :]
    return out


def null_summary(observed: dict, draws: list, keys=None) -> dict:
    """Compare a dict of statistics against a list of null dicts.

    Returns {key: dict(real, null_mean, null_sd, z, p)}. The z-score is the
    number of null standard deviations, which is the informative quantity when
    few draws are available (p is floored by the draw count).
    """
    keys = keys or [k for k, v in observed.items()
                    if np.isscalar(v) or np.ndim(v) == 0]
    out = {}
    for k in keys:
        v = np.array([d[k] for d in draws], float)
        sd = v.std() if v.std() > 0 else np.nan
        out[k] = dict(real=float(observed[k]), null_mean=float(v.mean()),
                      null_sd=float(v.std()),
                      z=float((observed[k] - v.mean()) / sd) if sd == sd else np.nan,
                      p=empirical_p(float(observed[k]), v))
    return out
